"""GitHub integration — create branches and PRs with AI-generated fixes."""

from github import Github, GithubException
from config import Config
from utils.logger import get_logger

log = get_logger("github")


def create_fix_pr(incident) -> str:
    """Create a GitHub PR with the fix for the given incident.

    Args:
        incident: An Incident model instance with fixed_code populated.

    Returns:
        The URL of the created pull request.
    """
    if not Config.GITHUB_TOKEN:
        raise ValueError("GITHUB_TOKEN not configured")
    if not Config.GITHUB_REPO:
        raise ValueError("GITHUB_REPO not configured (expected 'owner/repo')")
    if not incident.fixed_code:
        raise ValueError("No fix code available for this incident")

    g = Github(Config.GITHUB_TOKEN)
    repo = g.get_repo(Config.GITHUB_REPO)

    branch_name = f"autoduty/fix-incident-{incident.id}"
    affected_file = incident.affected_file or incident.source_file

    log.info("Creating PR branch '%s' for file '%s'", branch_name, affected_file)

    # Get the default branch SHA
    base_branch = repo.get_branch(incident.branch or "main")
    base_sha = base_branch.commit.sha

    # Create the new branch
    try:
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)
        log.info("Branch '%s' created", branch_name)
    except GithubException as e:
        if e.status == 422:
            log.warning("Branch '%s' already exists, updating it", branch_name)
        else:
            raise

    # Get the current file to obtain its SHA (needed for update)
    try:
        file_contents = repo.get_contents(affected_file, ref=branch_name)
        file_sha = file_contents.sha
        repo.update_file(
            path=affected_file,
            message=f"fix: AutoDuty fix for incident {incident.id}\n\n{incident.fix_description}",
            content=incident.fixed_code,
            sha=file_sha,
            branch=branch_name,
        )
    except GithubException:
        # File doesn't exist yet — create it
        repo.create_file(
            path=affected_file,
            message=f"fix: AutoDuty fix for incident {incident.id}\n\n{incident.fix_description}",
            content=incident.fixed_code,
            branch=branch_name,
        )

    # Build the PR body
    sandbox_status = ""
    if incident.sandbox_reproduced is not None:
        reproduced = "PASS" if incident.sandbox_reproduced else "SKIP"
        verified = "PASS" if incident.sandbox_fix_verified else "FAIL"
        sandbox_status = f"""
## Sandbox Verification
| Check | Result |
|-------|--------|
| Bug Reproduced | {reproduced} |
| Fix Verified | {verified} |

<details>
<summary>Sandbox Output</summary>

```
{incident.sandbox_output or 'N/A'}
```
</details>
"""

    pr_body = f"""## AutoDuty Automated Fix

**Incident ID:** `{incident.id}`
**Root Cause:** {incident.root_cause}
**Fix:** {incident.fix_description}

### Affected File
`{affected_file}`

{sandbox_status}

---
*This PR was automatically generated by [AutoDuty](https://github.com/autoduty) — your AI SRE.*
"""

    # Create the PR
    pr = repo.create_pull(
        title=f"[AutoDuty] Fix: {incident.root_cause[:80]}",
        body=pr_body,
        head=branch_name,
        base=incident.branch or "main",
    )

    log.info("PR #%s created: %s", pr.number, pr.html_url)
    return pr.html_url
